import type { ThemePreset } from './index';
import type { SerializableTheme } from '../types';

const classicTheme: SerializableTheme = {
  id: 'classic',
  containerBg: 'min-h-screen bg-gradient-to-b from-amber-50 via-white to-amber-50',
  sectionPadding: 'py-8 md:py-12 px-6',
  contentMaxWidth: 'max-w-2xl mx-auto',
  galleryMaxWidth: 'max-w-4xl mx-auto',
  headingClass: 'text-xl md:text-2xl font-serif text-center text-gray-800 mb-8 md:mb-12',
  bodyText: 'text-sm md:text-base text-gray-700 leading-relaxed whitespace-pre-line',
  nameClass: 'text-2xl md:text-3xl font-serif text-gray-800 mb-3 md:mb-4',
  labelClass: 'text-xs md:text-sm text-amber-800 mb-3 md:mb-4 font-medium',
  cardClass: 'flex items-start gap-3 md:gap-4 p-4 md:p-6 bg-white rounded-lg shadow-sm border border-amber-100',
  accountCardClass: 'p-4 md:p-5 bg-white rounded-xl shadow-sm border border-amber-100',
  iconColor: 'text-amber-600',
  accentColor: 'text-amber-600 hover:text-amber-700',
  sideLabel: 'text-sm md:text-base text-amber-800 mb-3 font-semibold',
  phoneLinkClass: 'inline-flex items-center gap-2 text-sm text-gray-600 hover:text-amber-600 transition-colors py-2 px-3 -mx-3 min-h-[44px]',
  accountTypeLabel: 'text-xs text-slate-500 mb-2',
  accountName: 'text-sm md:text-base text-gray-800 font-medium mb-1',
  accountDetail: 'text-xs md:text-sm text-gray-600',
  accountHolder: 'text-xs text-gray-500',
  noticeBg: 'p-4 md:p-6 bg-amber-50 rounded-lg',
  mapInfoBg: 'mt-4 p-4 bg-amber-50/60 rounded-lg',
  transportCard: 'mt-4 p-4 bg-white rounded-lg border border-amber-100',
  sectionBg: { parents: 'bg-amber-50/30', gallery: 'bg-amber-50/30', rsvp: 'bg-amber-50/30', ending: 'bg-amber-50/30' },
  endingImageClass: 'w-full h-64 md:h-80 object-cover rounded-lg',
  endingMessageClass: 'text-sm md:text-base text-gray-700 leading-relaxed whitespace-pre-line text-center font-serif',
  greetingDecorTop: { type: 'emoji', emoji: '\u{1F338}', symbolClass: 'text-3xl md:text-4xl' },
  greetingDecorBottom: undefined,
  greetingMaxWidth: 'max-w-2xl w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-3 md:gap-4',
  galleryItemClass: 'aspect-square overflow-hidden rounded-lg shadow-md cursor-pointer',
  galleryHover: 'hover:scale-110 transition-transform duration-300',
  galleryItemAnimation: { preset: 'fade-scale', staggerDelay: 0.1 },
  parentsGrid: 'grid md:grid-cols-2 gap-8 md:gap-12',
  groomAnimation: { preset: 'slide-x-left' },
  brideAnimation: { preset: 'slide-x-right' },
  accountsSpacing: 'space-y-6 md:space-y-8',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'font-medium text-sm md:text-base text-gray-800 mb-1 md:mb-2',
  cardValueClass: 'text-sm md:text-base text-gray-600',
  cardSubTextClass: 'text-xs md:text-sm text-gray-600',
  noticeTextClass: 'text-xs md:text-sm text-gray-600 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-gray-700 mb-2',
  transportTextClass: 'text-xs text-gray-600 leading-relaxed whitespace-pre-line',
  ceremonyDateLabel: '예식 일시',
  ceremonyVenueLabel: '예식 장소',
  mapVenueNameClass: 'text-sm font-medium text-gray-800',
  mapAddressClass: 'text-xs text-gray-600 mt-1',
  mapShowTel: true,
  sectionDivider: undefined,
  postCoverDivider: undefined,
  calendarAccentColor: 'bg-amber-600 text-white',
  calendarTodayColor: 'ring-2 ring-amber-300',
  calendarHeaderClass: 'text-sm font-serif text-gray-700',
  calendarDayClass: 'text-xs text-gray-600',
  countdownNumberClass: 'text-4xl font-serif text-amber-700',
  countdownLabelClass: 'text-xs text-gray-500',
  countdownUnitClass: 'text-[10px] text-gray-400',
  rsvpInputClass: 'border-amber-200 focus:ring-2 focus:ring-amber-500 focus:border-transparent',
  rsvpActiveClass: 'bg-amber-600 text-white',
  rsvpInactiveClass: 'bg-amber-50 text-amber-800 hover:bg-amber-100',
  rsvpSubmitClass: 'bg-amber-600 hover:bg-amber-700 text-white',
  cover: {
    layout: 'center',
    imageOverlay: 'bg-gradient-to-b from-transparent via-white/50 to-white',
    imageClass: 'opacity-40',
    topDecoration: { type: 'emoji', emoji: '\u2728', symbolClass: 'text-5xl md:text-6xl', className: 'mb-6' },
    labelText: 'Wedding Invitation',
    labelClass: 'font-serif text-xs md:text-sm tracking-[0.3em] text-amber-800 mb-6 md:mb-8 uppercase',
    nameClass: 'font-serif text-3xl md:text-4xl text-gray-800',
    nameDivider: 'ampersand',
    ampersandClass: 'text-xl md:text-2xl text-amber-600',
    dateClass: 'text-base md:text-lg text-gray-600',
    animation: { preset: 'slide-y', duration: 1, delay: 0.2 },
    motionClass: 'relative z-10 text-center px-6',
  },
  footer: {
    layout: 'centered',
    containerClass: 'py-8 md:py-12 px-6 text-center text-xs md:text-sm text-gray-500 border-t border-amber-100',
    linkClass: 'text-amber-600 hover:text-amber-700',
  },
};

export const classicPresets: ThemePreset[] = [
  {
    id: 'classic',
    name: '클래식',
    category: 'classic',
    description: '전통적인 웨딩 스타일',
    premium: false,
    preview: { primary: '#d97706', secondary: '#fef3c7', accent: '#d97706', bg: '#fffbeb' },
    theme: classicTheme,
  },
];
