import type { ThemePreset } from './index';
import type { SerializableTheme } from '../types';

const elegantTheme: SerializableTheme = {
  id: 'elegant',
  containerBg: 'min-h-screen bg-gradient-to-b from-amber-50/30 via-white to-slate-50',
  sectionPadding: 'py-12 md:py-16 px-6',
  galleryLayout: 'grid-2-1',
  parentsFullHeight: true,
  ceremonyLayout: 'timeline',
  sectionSpacing: 'spacious',
  contentMaxWidth: 'max-w-2xl mx-auto',
  galleryMaxWidth: 'max-w-4xl mx-auto',
  headingClass: 'text-xl md:text-2xl font-serif text-center text-slate-800 mb-8 md:mb-12',
  bodyText: 'text-sm md:text-base text-slate-600 leading-relaxed whitespace-pre-line font-light',
  nameClass: 'text-2xl md:text-3xl font-serif text-white mb-3',
  labelClass: 'text-xs tracking-[0.3em] text-amber-400/80 uppercase mb-4',
  cardClass: 'flex items-start gap-4 p-6 bg-white rounded-lg border border-slate-200 shadow-sm',
  accountCardClass: 'p-4 bg-white rounded-lg border border-slate-200 text-center',
  iconColor: 'text-amber-500',
  accentColor: 'text-amber-600 hover:text-amber-700',
  sideLabel: 'text-sm font-semibold text-slate-700 mb-4 text-center',
  phoneLinkClass: 'inline-flex items-center gap-2 text-sm text-slate-400 hover:text-amber-400 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-xs text-slate-400 mb-1',
  accountName: 'text-sm font-medium text-slate-800',
  accountDetail: 'text-sm text-slate-500 mt-1',
  accountHolder: 'text-xs text-slate-400 mt-0.5',
  noticeBg: 'p-6 bg-amber-50/50 rounded-lg border border-amber-100',
  mapInfoBg: 'mt-6 p-4 bg-white rounded-lg border border-slate-200 text-center',
  transportCard: 'mt-4 p-4 bg-white rounded-lg border border-slate-200',
  sectionBg: { parents: 'bg-slate-800', gallery: 'bg-slate-800', map: 'bg-slate-50', rsvp: 'bg-slate-50', ending: 'bg-slate-50' },
  endingImageClass: 'w-full h-64 md:h-80 object-cover rounded-lg',
  endingMessageClass: 'text-sm md:text-base text-slate-600 leading-relaxed whitespace-pre-line text-center font-light',
  greetingDecorTop: { type: 'diamond-with-lines', lineColor: 'to-amber-400/60', lineSize: 'w-16', symbolClass: 'w-2 h-2 rotate-45 border border-amber-400/60 mx-4' },
  greetingDecorBottom: { type: 'diamond-with-lines', lineColor: 'to-amber-400/60', lineSize: 'w-16', symbolClass: 'w-2 h-2 rotate-45 border border-amber-400/60 mx-4' },
  greetingMaxWidth: 'max-w-2xl w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-3',
  galleryItemClass: 'aspect-square overflow-hidden rounded-lg cursor-pointer',
  galleryHover: 'hover:scale-110 transition-transform duration-500',
  galleryItemAnimation: { preset: 'scale', staggerDelay: 0.08 },
  parentsGrid: 'grid md:grid-cols-2 gap-10',
  parentsRoleLabel: true,
  parentsFamilyNameClass: 'text-xs text-slate-400 mb-2',
  groomAnimation: { preset: 'slide-y' },
  brideAnimation: { preset: 'slide-y', delay: 0.1 },
  accountsSpacing: 'space-y-8',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'text-xs tracking-[0.2em] text-slate-400 uppercase mb-2',
  cardValueClass: 'text-base text-slate-800',
  cardSubTextClass: 'text-sm text-slate-500',
  noticeTextClass: 'text-sm text-slate-600 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-slate-700 mb-2',
  transportTextClass: 'text-sm text-slate-600 leading-relaxed whitespace-pre-line',
  ceremonyDateLabel: 'Date & Time',
  ceremonyVenueLabel: 'Location',
  mapVenueNameClass: 'text-base font-medium text-slate-800',
  mapAddressClass: 'text-sm text-slate-500 mt-1',
  sectionDivider: undefined,
  postCoverDivider: undefined,
  calendarAccentColor: 'bg-amber-500 text-white',
  calendarTodayColor: 'ring-2 ring-amber-300',
  calendarHeaderClass: 'text-xs tracking-[0.2em] text-slate-500 uppercase',
  calendarDayClass: 'text-xs text-slate-500',
  countdownNumberClass: 'text-5xl font-serif text-slate-800',
  countdownLabelClass: 'text-xs tracking-[0.2em] text-amber-500 uppercase',
  countdownUnitClass: 'text-[10px] text-slate-400',
  rsvpInputClass: 'border-slate-200 focus:ring-2 focus:ring-amber-500 focus:border-transparent',
  rsvpActiveClass: 'bg-amber-500 text-white',
  rsvpInactiveClass: 'bg-slate-100 text-slate-600 hover:bg-slate-200',
  rsvpSubmitClass: 'bg-amber-600 hover:bg-amber-700 text-white',
  galleryHeading: { type: 'with-sub-label', subLabel: 'Moments', subLabelClass: 'text-xs tracking-[0.3em] text-amber-500 uppercase mb-2', headingClass: 'text-xl md:text-2xl font-serif text-slate-800', className: 'text-center mb-10' },
  accountsHeading: { type: 'with-sub-label', subLabel: 'Gift', subLabelClass: 'text-xs tracking-[0.3em] text-amber-500 uppercase mb-2', headingClass: 'text-xl md:text-2xl font-serif text-slate-800', className: 'text-center mb-10' },
  mapHeading: { type: 'with-sub-label', subLabel: 'Location', subLabelClass: 'text-xs tracking-[0.3em] text-amber-500 uppercase mb-2', headingClass: 'text-xl md:text-2xl font-serif text-slate-800', className: 'text-center mb-10' },
  cover: {
    layout: 'center',
    imageOverlay: 'bg-gradient-to-b from-slate-900/20 via-transparent to-white',
    imageClass: 'opacity-30',
    topDecoration: { type: 'diamond-with-lines', lineColor: 'to-amber-400', lineSize: 'w-12', symbolClass: 'w-3 h-3 rotate-45 border-2 border-amber-400 mx-3', className: 'flex items-center justify-center mb-8' },
    bottomDecoration: { type: 'diamond-with-lines', lineColor: 'to-amber-400', lineSize: 'w-12', symbolClass: 'w-3 h-3 rotate-45 border-2 border-amber-400 mx-3', className: 'flex items-center justify-center mb-8' },
    labelText: 'Wedding Invitation',
    labelClass: 'text-xs tracking-[0.4em] text-amber-600 uppercase mb-8',
    nameClass: 'font-serif text-4xl md:text-5xl text-slate-800',
    nameWrapperClass: 'space-y-4 mb-10',
    nameDivider: 'ampersand',
    ampersandClass: 'text-2xl text-amber-500 font-light',
    dateClass: 'text-sm tracking-wide text-slate-600',
    venueClass: 'text-sm tracking-wide text-slate-600 mt-4',
    animation: { preset: 'slide-y', duration: 1, delay: 0.2 },
    motionClass: 'relative z-10 text-center px-6',
  },
  footer: {
    layout: 'centered',
    topDecoration: { type: 'diamond-with-lines', lineColor: 'to-amber-400/40', lineSize: 'w-8', symbolClass: 'w-2 h-2 rotate-45 border border-amber-400/40 mx-3', className: 'flex items-center justify-center mb-4' },
    containerClass: 'py-10 md:py-14 px-6 text-center bg-slate-800',
    nameClass: 'text-sm text-slate-400',
    linkClass: 'text-xs text-slate-500 hover:text-amber-400 transition-colors',
  },
};

export const elegantPresets: ThemePreset[] = [
  {
    id: 'elegant',
    name: '엘레강스',
    category: 'elegant',
    description: '호텔웨딩 고급 스타일',
    premium: false,
    preview: { primary: '#f59e0b', secondary: '#334155', accent: '#f59e0b', bg: '#fffbeb' },
    theme: elegantTheme,
  },
];
