import type { ThemePreset } from './index';
import type { SerializableTheme } from '../types';

const modernTheme: SerializableTheme = {
  id: 'modern',
  containerBg: 'min-h-screen bg-zinc-50',
  sectionPadding: 'py-12 md:py-16 px-8 md:px-12',
  galleryLayout: 'grid-3',
  parentsLayout: 'stacked',
  parentsFullHeight: false,
  greetingLayout: 'left-aligned',
  ceremonyLayout: 'inline',
  sectionSpacing: 'spacious',
  contentMaxWidth: 'max-w-2xl',
  galleryMaxWidth: 'max-w-4xl',
  headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-6',
  bodyText: 'text-base md:text-lg text-zinc-600 leading-relaxed whitespace-pre-line',
  nameClass: 'text-2xl md:text-3xl font-sans font-bold text-zinc-900 mb-3',
  labelClass: 'text-xs text-zinc-400 mb-2',
  cardClass: 'flex items-start gap-4',
  accountCardClass: 'py-4 border-b border-zinc-200',
  iconColor: 'text-emerald-500',
  accentColor: 'text-emerald-600 hover:text-emerald-700',
  sideLabel: 'text-sm font-semibold text-zinc-800 mb-4',
  phoneLinkClass: 'inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-emerald-600 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-xs text-zinc-400 mb-1',
  accountName: 'text-sm text-zinc-800 font-medium',
  accountDetail: 'text-sm text-zinc-500 mt-1',
  accountHolder: 'text-xs text-zinc-400 mt-0.5',
  noticeBg: 'border-l-2 border-emerald-400 pl-4',
  mapInfoBg: 'mt-6 space-y-2',
  transportCard: 'mt-6 p-4 bg-zinc-100 rounded-lg',
  sectionBg: { gallery: 'bg-zinc-100', ending: 'bg-zinc-100' },
  endingImageClass: 'w-full h-64 md:h-80 object-cover',
  endingMessageClass: 'text-base md:text-lg text-zinc-600 leading-relaxed whitespace-pre-line',
  greetingDecorTop: { type: 'text-label', text: 'Greeting', className: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-6' },
  greetingDecorBottom: undefined,
  greetingMaxWidth: 'max-w-2xl w-full',
  greetingAlign: '',
  galleryGap: 'gap-2',
  galleryItemClass: 'aspect-square overflow-hidden cursor-pointer',
  galleryHover: 'hover:scale-105 transition-transform duration-500',
  galleryItemAnimation: { preset: 'scale', staggerDelay: 0.08 },
  parentsGrid: 'grid md:grid-cols-2 gap-12',
  parentsHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-10' },
  groomAnimation: { preset: 'slide-x-left', duration: 0.5 },
  brideAnimation: { preset: 'slide-x-right', duration: 0.5 },
  accountsSpacing: 'space-y-8',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'text-xs text-zinc-400 uppercase tracking-wide mb-1',
  cardValueClass: 'text-base text-zinc-800',
  cardSubTextClass: 'text-sm text-zinc-500',
  noticeTextClass: 'text-sm text-zinc-500 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-zinc-700 mb-2',
  transportTextClass: 'text-sm text-zinc-600 whitespace-pre-line leading-relaxed',
  ceremonyHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-6' },
  ceremonyDateLabel: 'Date & Time',
  ceremonyVenueLabel: 'Location',
  mapVenueNameClass: 'text-base font-medium text-zinc-800',
  mapAddressClass: 'text-sm text-zinc-500',
  sectionDivider: { type: 'horizontal-line', color: 'bg-zinc-200', className: 'mx-8 md:mx-12' },
  postCoverDivider: { type: 'gradient-line', color: 'from-transparent via-emerald-500/40 to-transparent' },
  calendarAccentColor: 'bg-emerald-600 text-white',
  calendarTodayColor: 'ring-2 ring-emerald-300',
  calendarHeaderClass: 'text-sm font-medium text-zinc-700',
  calendarDayClass: 'text-xs text-zinc-500',
  countdownNumberClass: 'text-5xl font-bold text-zinc-900',
  countdownLabelClass: 'text-xs text-zinc-400 uppercase tracking-wider',
  countdownUnitClass: 'text-[10px] text-zinc-400',
  rsvpInputClass: 'border-zinc-200 focus:ring-2 focus:ring-emerald-500 focus:border-transparent',
  rsvpActiveClass: 'bg-emerald-600 text-white',
  rsvpInactiveClass: 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200',
  rsvpSubmitClass: 'bg-emerald-600 hover:bg-emerald-700 text-white',
  galleryHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-10' },
  accountsHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-10' },
  mapHeading: { type: 'text-label', headingClass: 'text-xs tracking-[0.3em] text-emerald-600 uppercase mb-6' },
  cover: {
    layout: 'bottom-left',
    imageOverlay: 'bg-gradient-to-t from-zinc-900/80 via-zinc-900/30 to-transparent',
    fallbackBg: 'bg-gradient-to-br from-zinc-800 to-zinc-900',
    labelText: 'Wedding Invitation',
    labelClass: 'text-xs tracking-[0.4em] text-emerald-400 uppercase mb-4',
    nameClass: 'text-5xl md:text-7xl font-sans font-bold text-white leading-tight mb-2',
    nameDivider: 'lines-with-ampersand',
    ampersandClass: 'text-emerald-400 text-lg',
    nameDividerLineClass: 'w-12 bg-emerald-400',
    dateClass: 'text-sm text-zinc-300 space-y-1',
    venueClass: 'text-zinc-400',
    animation: { preset: 'slide-x-left', duration: 0.8, delay: 0.2 },
    motionClass: 'relative z-10 px-8 md:px-12 w-full',
  },
  footer: {
    layout: 'flex-between',
    containerClass: 'py-10 md:py-14 px-8 md:px-12 border-t border-zinc-200',
    linkClass: 'hover:text-emerald-600 transition-colors',
  },
};

const minimalTheme: SerializableTheme = {
  id: 'minimal',
  containerBg: 'min-h-screen bg-white',
  sectionPadding: 'py-10 md:py-16 px-6',
  galleryLayout: 'single-column',
  parentsLayout: 'compact',
  parentsFullHeight: false,
  greetingLayout: 'quote-style',
  ceremonyLayout: 'centered',
  sectionSpacing: 'normal',
  contentMaxWidth: 'max-w-md mx-auto',
  galleryMaxWidth: 'max-w-3xl mx-auto',
  headingClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase text-center mb-8 font-myeongjo',
  bodyText: 'text-sm md:text-base text-stone-500 leading-loose whitespace-pre-line tracking-wide font-myeongjo font-light',
  nameClass: 'text-xl font-myeongjo font-light tracking-[0.1em] text-stone-900 mb-3',
  labelClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase mb-4',
  cardClass: 'text-center',
  accountCardClass: 'py-3',
  iconColor: 'text-stone-300',
  accentColor: 'text-stone-400 hover:text-stone-600',
  sideLabel: 'text-xs font-medium text-stone-700 mb-4 tracking-wide',
  phoneLinkClass: 'inline-flex items-center gap-1.5 text-xs text-stone-400 hover:text-stone-600 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-[10px] text-stone-400 mb-1',
  accountName: 'text-xs text-stone-700',
  accountDetail: 'text-xs text-stone-400 mt-1',
  accountHolder: 'text-[10px] text-stone-300 mt-0.5',
  noticeBg: 'pt-6',
  mapInfoBg: 'mt-6 space-y-1',
  transportCard: 'mt-6 pt-6',
  sectionBg: {},
  endingImageClass: 'w-full h-64 md:h-80 object-cover',
  endingMessageClass: 'text-sm md:text-base text-stone-500 leading-loose whitespace-pre-line text-center tracking-wide font-myeongjo font-light',
  greetingDecorTop: undefined,
  greetingDecorBottom: undefined,
  greetingMaxWidth: 'max-w-md w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-1',
  galleryItemClass: 'aspect-square overflow-hidden cursor-pointer',
  galleryHover: 'hover:opacity-80 transition-opacity duration-300',
  galleryItemAnimation: { preset: 'fade', staggerDelay: 0.05 },
  parentsGrid: 'grid grid-cols-2 gap-12',
  parentsRoleLabel: true,
  parentsFamilyNameClass: 'text-xs text-stone-400 mb-2',
  groomAnimation: { preset: 'fade', duration: 0.6 },
  brideAnimation: { preset: 'fade', duration: 0.6, delay: 0.1 },
  accountsSpacing: 'space-y-10',
  accountCardsSpacing: 'space-y-4',
  accountsDivider: { type: 'horizontal-line', color: 'bg-stone-200', size: 'w-8', className: 'flex justify-center' },
  cardLabelClass: '',
  cardValueClass: 'text-sm text-stone-700 tracking-wide',
  cardSubTextClass: 'text-xs text-stone-400 tracking-wide',
  noticeTextClass: 'text-xs text-stone-400 whitespace-pre-line leading-relaxed tracking-wide',
  transportLabelClass: '',
  transportTextClass: 'text-xs text-stone-400 whitespace-pre-line leading-relaxed tracking-wide',
  ceremonyCentered: true,
  ceremonyDateLabel: 'Date & Time',
  ceremonyVenueLabel: 'Location',
  ceremonyNoticeDivider: { type: 'horizontal-line', color: 'bg-stone-200', size: 'w-8', className: 'flex justify-center mb-6' },
  mapVenueNameClass: 'text-sm text-stone-800 font-medium tracking-wide',
  mapAddressClass: 'text-xs text-stone-400 tracking-wide',
  transportTopDivider: { type: 'horizontal-line', color: 'bg-stone-200', size: 'w-8', className: 'flex justify-center mb-6' },
  sectionDivider: { type: 'vertical-line', color: 'bg-stone-200', size: 'h-12', className: 'py-4' },
  postCoverDivider: { type: 'vertical-line', color: 'bg-stone-200', size: 'h-12', className: 'py-4' },
  calendarAccentColor: 'bg-stone-800 text-white',
  calendarTodayColor: 'ring-1 ring-stone-300',
  calendarHeaderClass: 'text-[10px] tracking-[0.2em] text-stone-400 uppercase',
  calendarDayClass: 'text-[10px] text-stone-400',
  countdownNumberClass: 'text-5xl font-myeongjo font-light tracking-wide text-stone-800',
  countdownLabelClass: 'text-[10px] tracking-[0.2em] text-stone-400 uppercase',
  countdownUnitClass: 'text-[10px] text-stone-300',
  rsvpInputClass: 'border-stone-300 focus:ring-1 focus:ring-stone-900 focus:border-transparent',
  rsvpActiveClass: 'bg-zinc-900 text-white',
  rsvpInactiveClass: 'bg-stone-100 text-stone-500 hover:bg-stone-200',
  rsvpSubmitClass: 'bg-zinc-900 hover:bg-zinc-800 text-white',
  galleryHeading: { type: 'text-label', headingClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase text-center mb-12' },
  accountsHeading: { type: 'text-label', headingClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase mb-12' },
  mapHeading: { type: 'text-label', headingClass: 'text-[10px] tracking-[0.3em] text-stone-400 uppercase mb-8' },
  cover: {
    layout: 'center',
    imageClass: 'opacity-20 grayscale',
    labelText: 'Wedding Invitation',
    labelClass: 'text-[10px] tracking-[0.5em] text-stone-400 uppercase mb-16 font-myeongjo',
    nameClass: 'text-3xl md:text-4xl font-myeongjo font-light tracking-[0.15em] text-stone-900',
    nameDivider: 'lines-only',
    nameDividerLineClass: 'w-16 bg-stone-300',
    dateClass: 'text-xs tracking-[0.2em] text-stone-400',
    venueClass: 'text-xs tracking-[0.2em] text-stone-400 mt-4',
    nameWrapperClass: 'space-y-6 mb-16',
    animation: { preset: 'fade', duration: 1.2, delay: 0.3 },
    motionClass: 'relative z-10 text-center px-6',
  },
  footer: {
    layout: 'centered',
    topDivider: { type: 'horizontal-line', color: 'bg-stone-200', size: 'w-8', className: 'flex justify-center mb-8' },
    containerClass: 'py-12 md:py-16 px-6 text-center',
    nameClass: 'text-[10px] tracking-[0.3em] text-stone-300',
    linkClass: 'text-[10px] tracking-[0.2em] text-stone-300 hover:text-stone-500 transition-colors',
  },
};

export const modernPresets: ThemePreset[] = [
  {
    id: 'modern',
    name: '모던',
    category: 'modern',
    description: '대담한 타이포그래피',
    premium: false,
    preview: { primary: '#059669', secondary: '#27272a', accent: '#10b981', bg: '#fafafa' },
    theme: modernTheme,
  },
  {
    id: 'minimal',
    name: '미니멀',
    category: 'modern',
    description: '여백의 미, 흑백 톤',
    premium: false,
    preview: { primary: '#78716c', secondary: '#f5f5f4', accent: '#1c1917', bg: '#ffffff' },
    theme: minimalTheme,
  },
];
