import type { ThemePreset } from './index';
import type { SerializableTheme } from '../types';

const naturalTheme: SerializableTheme = {
  id: 'natural',
  containerBg: 'min-h-screen bg-gradient-to-b from-stone-50 via-emerald-50/20 to-stone-50',
  sectionPadding: 'py-10 md:py-16 px-6',
  galleryLayout: 'grid-2',
  parentsLayout: 'cards',
  parentsFullHeight: false,
  sectionSpacing: 'normal',
  contentMaxWidth: 'max-w-2xl mx-auto',
  galleryMaxWidth: 'max-w-4xl mx-auto',
  headingClass: 'text-xl md:text-2xl font-batang font-light text-center text-stone-800 mb-8 md:mb-12',
  bodyText: 'text-sm md:text-base text-stone-600 leading-loose whitespace-pre-line',
  nameClass: 'text-2xl md:text-3xl font-batang font-light text-stone-800 mb-3',
  labelClass: 'text-xs tracking-[0.2em] text-emerald-600/70 uppercase mb-3',
  cardClass: 'flex items-start gap-4 p-6 bg-white rounded-2xl border border-emerald-100 shadow-sm',
  accountCardClass: 'p-4 bg-white/80 rounded-2xl border border-emerald-100 text-center',
  iconColor: 'text-emerald-500',
  accentColor: 'text-emerald-600 hover:text-emerald-700',
  sideLabel: 'text-sm font-medium text-emerald-700 mb-4 text-center',
  phoneLinkClass: 'inline-flex items-center gap-2 text-sm text-stone-500 hover:text-emerald-600 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-xs text-stone-400 mb-1',
  accountName: 'text-sm font-medium text-stone-800',
  accountDetail: 'text-sm text-stone-500 mt-1',
  accountHolder: 'text-xs text-stone-400 mt-0.5',
  noticeBg: 'p-6 bg-emerald-50/50 rounded-2xl border border-emerald-100',
  mapInfoBg: 'mt-6 p-4 bg-white/80 rounded-2xl border border-emerald-100 text-center',
  transportCard: 'mt-4 p-4 bg-white/80 rounded-2xl border border-emerald-100',
  sectionBg: { parents: 'bg-emerald-50/30', accounts: 'bg-emerald-50/30', map: 'bg-emerald-50/30', ending: 'bg-emerald-50/30' },
  endingImageClass: 'w-full h-64 md:h-80 object-cover rounded-2xl',
  endingMessageClass: 'text-sm md:text-base text-stone-600 leading-loose whitespace-pre-line text-center',
  greetingDecorTop: { type: 'emoji', emoji: '\u{1F33F}', symbolClass: 'text-xl opacity-60' },
  greetingDecorBottom: { type: 'emoji', emoji: '\u{1F33F}', symbolClass: 'text-xl opacity-60' },
  greetingMaxWidth: 'max-w-2xl w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-4',
  galleryItemClass: 'aspect-square overflow-hidden rounded-2xl cursor-pointer shadow-sm',
  galleryHover: 'hover:scale-105 transition-transform duration-500',
  galleryItemAnimation: { preset: 'slide-y', staggerDelay: 0.08 },
  parentsGrid: 'grid md:grid-cols-2 gap-10',
  parentsCardWrapper: 'text-center p-6 bg-white/60 rounded-2xl',
  parentsRoleLabel: true,
  parentsFamilyNameClass: 'text-xs text-stone-400 mb-2',
  groomAnimation: { preset: 'slide-x-left' },
  brideAnimation: { preset: 'slide-x-right' },
  accountsSpacing: 'space-y-8',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'text-xs tracking-[0.15em] text-emerald-600/70 uppercase mb-2',
  cardValueClass: 'text-base text-stone-700',
  cardSubTextClass: 'text-sm text-stone-500',
  noticeTextClass: 'text-sm text-stone-600 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-stone-700 mb-2',
  transportTextClass: 'text-sm text-stone-600 leading-relaxed whitespace-pre-line',
  ceremonyDateLabel: 'Date & Time',
  ceremonyVenueLabel: 'Location',
  mapVenueNameClass: 'text-base font-medium text-stone-800',
  mapAddressClass: 'text-sm text-stone-500 mt-1',
  sectionDivider: undefined,
  postCoverDivider: undefined,
  calendarAccentColor: 'bg-emerald-500 text-white',
  calendarTodayColor: 'ring-2 ring-emerald-200',
  calendarHeaderClass: 'text-sm font-light text-stone-600',
  calendarDayClass: 'text-xs text-stone-500',
  countdownNumberClass: 'text-4xl font-light text-stone-800',
  countdownLabelClass: 'text-xs tracking-[0.15em] text-emerald-600/70 uppercase',
  countdownUnitClass: 'text-[10px] text-stone-400',
  rsvpInputClass: 'border-emerald-200 focus:ring-2 focus:ring-emerald-400 focus:border-transparent',
  rsvpActiveClass: 'bg-emerald-500 text-white',
  rsvpInactiveClass: 'bg-stone-100 text-stone-600 hover:bg-stone-200',
  rsvpSubmitClass: 'bg-emerald-500 hover:bg-emerald-600 text-white',
  galleryHeading: { type: 'with-decoration', decoration: '\u{1F33F}', decorationClass: 'text-2xl opacity-60', headingClass: 'text-xl md:text-2xl font-light text-stone-800 mt-2', className: 'text-center mb-10' },
  accountsHeading: { type: 'with-decoration', decoration: '\u{1F33F}', decorationClass: 'text-2xl opacity-60', headingClass: 'text-xl md:text-2xl font-light text-stone-800 mt-2', className: 'text-center mb-10' },
  mapHeading: { type: 'with-decoration', decoration: '\u{1F33F}', decorationClass: 'text-2xl opacity-60', headingClass: 'text-xl md:text-2xl font-light text-stone-800 mt-2', className: 'text-center mb-10' },
  cover: {
    layout: 'center',
    imageOverlay: 'bg-gradient-to-b from-stone-50/50 via-transparent to-stone-50',
    imageClass: 'opacity-40',
    topDecoration: { type: 'emoji', emoji: '\u{1F343}', symbolClass: 'text-4xl opacity-40', className: 'mb-4' },
    bottomDecoration: { type: 'emoji', emoji: '\u{1F33F}', symbolClass: 'text-4xl opacity-40', className: 'mt-8' },
    labelText: 'Wedding Invitation',
    labelClass: 'text-xs tracking-[0.4em] text-emerald-600/80 uppercase mb-8',
    nameClass: 'font-batang font-light text-4xl md:text-5xl text-stone-800 tracking-wide',
    nameWrapperClass: 'space-y-4 mb-8',
    nameDivider: 'lines-with-ampersand',
    ampersandClass: 'text-emerald-500/70 text-lg',
    nameDividerLineClass: 'w-8 bg-emerald-400/50',
    dateClass: 'text-sm text-stone-500',
    venueClass: 'text-sm text-stone-500 mt-4',
    animation: { preset: 'slide-y', duration: 1, delay: 0.2 },
    motionClass: 'relative z-10 text-center px-6',
  },
  footer: {
    layout: 'centered',
    topDecoration: { type: 'emoji', emoji: '\u{1F33F}', symbolClass: 'text-lg opacity-40', className: 'flex items-center justify-center gap-2 mb-4' },
    containerClass: 'py-10 md:py-14 px-6 text-center',
    nameClass: 'text-sm text-stone-500',
    linkClass: 'text-xs text-stone-400 hover:text-emerald-600 transition-colors',
  },
};

export const naturalPresets: ThemePreset[] = [
  {
    id: 'natural',
    name: '내추럴',
    category: 'natural',
    description: '가든웨딩 자연 스타일',
    premium: false,
    preview: { primary: '#10b981', secondary: '#78716c', accent: '#059669', bg: '#fafaf9' },
    theme: naturalTheme,
  },
];
