import type { ThemePreset } from './index';
import type { SerializableTheme } from '../types';

const floralTheme: SerializableTheme = {
  id: 'floral',
  containerBg: 'min-h-screen bg-gradient-to-b from-rose-50 via-pink-50/30 to-rose-50',
  sectionPadding: 'py-8 md:py-12 px-6',
  galleryLayout: 'masonry',
  parentsLayout: 'cards',
  parentsFullHeight: true,
  ceremonyLayout: 'cards',
  sectionSpacing: 'normal',
  contentMaxWidth: 'max-w-lg mx-auto',
  galleryMaxWidth: 'max-w-4xl mx-auto',
  headingClass: 'font-batang text-xl text-center text-rose-800 mb-10',
  bodyText: 'font-batang text-sm md:text-base text-rose-800/70 leading-relaxed whitespace-pre-line',
  nameClass: 'font-batang text-2xl text-rose-900 mb-3',
  labelClass: 'text-xs text-rose-400 mb-3',
  cardClass: 'flex items-start gap-4 p-5 bg-white/60 rounded-2xl border border-rose-100',
  accountCardClass: 'p-4 bg-white/60 rounded-2xl border border-rose-100 text-center',
  iconColor: 'text-rose-400',
  accentColor: 'text-rose-400 hover:text-rose-600',
  sideLabel: 'text-sm text-rose-600 mb-3 font-semibold text-center',
  phoneLinkClass: 'inline-flex items-center gap-1.5 text-xs text-rose-400 hover:text-rose-600 transition-colors py-2 min-h-[44px]',
  accountTypeLabel: 'text-[10px] text-rose-400 mb-1',
  accountName: 'text-sm text-rose-900 font-medium',
  accountDetail: 'text-xs text-rose-500/70 mt-1',
  accountHolder: 'text-[10px] text-rose-400 mt-0.5',
  noticeBg: 'p-5 bg-pink-50/60 rounded-2xl border border-rose-100',
  mapInfoBg: 'mt-6 p-4 bg-white/60 rounded-2xl border border-rose-100 text-center',
  transportCard: 'mt-4 p-5 bg-pink-50/60 rounded-2xl border border-rose-100',
  sectionBg: { rsvp: 'bg-rose-50/30', ending: 'bg-rose-50/30' },
  endingImageClass: 'w-full h-64 md:h-80 object-cover rounded-2xl',
  endingMessageClass: 'font-batang text-sm md:text-base text-rose-800/70 leading-relaxed whitespace-pre-line text-center',
  greetingDecorTop: { type: 'symbol-with-lines', symbol: '\u2740', lineColor: 'to-rose-200', lineSize: 'w-12', symbolClass: 'text-rose-300 text-lg mx-3' },
  greetingDecorBottom: { type: 'symbol-with-lines', symbol: '\u2740', lineColor: 'to-rose-200', lineSize: 'w-12', symbolClass: 'text-rose-300 text-lg mx-3' },
  greetingMaxWidth: 'max-w-lg w-full',
  greetingAlign: 'text-center',
  galleryGap: 'gap-3',
  galleryItemClass: 'aspect-square overflow-hidden rounded-2xl shadow-sm cursor-pointer border border-rose-100',
  galleryHover: 'hover:scale-110 transition-transform duration-300',
  galleryItemAnimation: { preset: 'fade-scale', staggerDelay: 0.08 },
  parentsGrid: 'grid md:grid-cols-2 gap-8',
  parentsCardWrapper: 'text-center bg-white/50 rounded-2xl p-6 border border-rose-100',
  groomAnimation: { preset: 'scale', duration: 0.5 },
  brideAnimation: { preset: 'scale', duration: 0.5, delay: 0.1 },
  accountsSpacing: 'space-y-6',
  accountCardsSpacing: 'space-y-3',
  cardLabelClass: 'font-batang text-sm text-rose-800 mb-1',
  cardValueClass: 'text-sm text-rose-600/70',
  cardSubTextClass: 'text-xs text-rose-500/70',
  noticeTextClass: 'text-xs text-rose-500/70 whitespace-pre-line leading-relaxed',
  transportLabelClass: 'text-xs font-semibold text-rose-700 mb-2',
  transportTextClass: 'text-xs text-rose-500/70 whitespace-pre-line leading-relaxed',
  ceremonyDateLabel: '예식 일시',
  ceremonyVenueLabel: '예식 장소',
  mapVenueNameClass: 'text-sm text-rose-800 font-medium',
  mapAddressClass: 'text-xs text-rose-500/70 mt-1',
  sectionDivider: undefined,
  postCoverDivider: undefined,
  calendarAccentColor: 'bg-rose-500 text-white',
  calendarTodayColor: 'ring-2 ring-rose-200',
  calendarHeaderClass: 'text-sm font-batang text-rose-700',
  calendarDayClass: 'text-xs text-rose-400',
  countdownNumberClass: 'text-4xl font-batang text-rose-700',
  countdownLabelClass: 'text-xs text-rose-400',
  countdownUnitClass: 'text-[10px] text-rose-300',
  rsvpInputClass: 'border-rose-200 focus:ring-2 focus:ring-rose-400 focus:border-transparent',
  rsvpActiveClass: 'bg-rose-500 text-white',
  rsvpInactiveClass: 'bg-rose-50 text-rose-700 hover:bg-rose-100',
  rsvpSubmitClass: 'bg-rose-500 hover:bg-rose-600 text-white',
  mapHeading: { type: 'text-label', lineColor: 'to-rose-200', lineSize: 'w-12', headingClass: 'font-batang text-xl text-rose-800', className: 'flex items-center justify-center gap-3 mb-8' },
  cover: {
    layout: 'center',
    imageOverlay: 'bg-gradient-to-b from-rose-50/60 via-transparent to-rose-50',
    imageClass: 'opacity-30',
    topDecoration: { type: 'emoji', emoji: '\u{1F33A}', symbolClass: 'text-3xl opacity-60', className: 'mb-4' },
    bottomDecoration: { type: 'emoji', emoji: '\u{1F338}', symbolClass: 'text-3xl opacity-60', className: 'mt-8' },
    labelText: 'Wedding Invitation',
    labelClass: 'font-batang text-xs tracking-[0.3em] text-rose-400 mb-8',
    nameWrapperClass: 'inline-block bg-white/60 backdrop-blur-sm rounded-3xl px-10 py-8 shadow-sm border border-rose-100',
    nameClass: 'font-batang text-3xl md:text-4xl text-rose-900',
    nameDivider: 'ampersand',
    ampersandClass: 'text-rose-300 text-lg',
    dateClass: 'text-sm text-rose-500',
    venueClass: 'text-sm text-rose-400 mt-3',
    animation: { preset: 'slide-y', duration: 1, delay: 0.2 },
    motionClass: 'relative z-10 text-center px-6',
  },
  footer: {
    layout: 'centered',
    topDecoration: { type: 'symbol-with-lines', symbol: '\u2740', lineColor: 'to-rose-200', lineSize: 'w-8', symbolClass: 'text-rose-300 text-sm mx-3', className: 'flex items-center justify-center mb-6' },
    containerClass: 'py-10 md:py-14 px-6 text-center',
    nameClass: 'text-xs text-rose-400',
    linkClass: 'text-xs text-rose-300 hover:text-rose-500 transition-colors',
  },
};

export const romanticPresets: ThemePreset[] = [
  {
    id: 'floral',
    name: '플로럴',
    category: 'romantic',
    description: '꽃무늬 파스텔 디자인',
    premium: false,
    preview: { primary: '#f43f5e', secondary: '#fff1f2', accent: '#fb7185', bg: '#fff1f2' },
    theme: floralTheme,
  },
];
